# Generated by Django 5.2.7 on 2025-10-12 05:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wallet_address', models.CharField(help_text='Ethereum wallet address starting with 0x', max_length=42, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_wallet', message='Enter a valid Ethereum wallet address', regex='^0x[a-fA-F0-9]{40}$')])),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the user has completed KYC verification')),
                ('kyc_documents', models.JSONField(blank=True, help_text='JSON field storing KYC document references', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.BigIntegerField(help_text='Unique token ID from the blockchain', unique=True)),
                ('coordinates', models.JSONField(help_text='GeoJSON polygon coordinates of the land parcel')),
                ('area', models.DecimalField(decimal_places=2, help_text='Area of the land parcel in square meters', max_digits=12)),
                ('address', models.TextField(help_text='Physical address of the land parcel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the land parcel', max_length=20)),
                ('documents', models.JSONField(help_text='IPFS hashes of land documents')),
                ('metadata_uri', models.URLField(help_text='IPFS URI containing parcel metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Current owner of the land parcel', on_delete=django.db.models.deletion.PROTECT, related_name='owned_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'land parcel',
                'verbose_name_plural': 'land parcels',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', help_text='Current status of the dispute', max_length=20)),
                ('reason', models.TextField(help_text='Detailed reason for the dispute')),
                ('evidence', models.JSONField(help_text='IPFS hashes of evidence documents')),
                ('resolution', models.TextField(blank=True, help_text='Resolution details if dispute is resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complainant', models.ForeignKey(help_text='User who filed the dispute', on_delete=django.db.models.deletion.PROTECT, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(help_text='Land parcel under dispute', on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='land_registry.parcel')),
            ],
            options={
                'verbose_name': 'dispute',
                'verbose_name_plural': 'disputes',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(help_text='Ethereum transaction hash', max_length=66, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_hash', message='Enter a valid transaction hash', regex='^0x[a-fA-F0-9]{64}$')])),
                ('from_address', models.CharField(help_text='Transaction sender address', max_length=42, validators=[django.core.validators.RegexValidator(code='invalid_address', message='Enter a valid Ethereum address', regex='^0x[a-fA-F0-9]{40}$')])),
                ('to_address', models.CharField(help_text='Transaction recipient address', max_length=42, validators=[django.core.validators.RegexValidator(code='invalid_address', message='Enter a valid Ethereum address', regex='^0x[a-fA-F0-9]{40}$')])),
                ('transaction_type', models.CharField(choices=[('registration', 'Registration'), ('transfer', 'Transfer'), ('update', 'Update'), ('dispute', 'Dispute')], help_text='Type of transaction', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Additional transaction metadata', null=True)),
                ('timestamp', models.DateTimeField(help_text='Transaction timestamp from blockchain')),
                ('block_number', models.BigIntegerField(help_text='Block number containing the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(help_text='Related land parcel', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='land_registry.parcel')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
