# Generated by Django 5.2.7 on 2025-10-12 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_users', 'Can create new users and wallets'), ('can_verify_land', 'Can verify land registrations'), ('can_survey_land', 'Can survey and confirm land boundaries'), ('can_register_land', 'Can register land ownership'), ('can_audit_records', 'Can audit system records'), ('can_resolve_disputes', 'Can resolve property disputes')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolver',
            field=models.ForeignKey(blank=True, help_text='Court authority who resolved the dispute', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Generated QR code for public verification', null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='verification_data',
            field=models.JSONField(blank=True, help_text='OCR and AI verification results', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.TextField(blank=True, help_text='Encrypted private key for the wallet', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('surveyor', 'Surveyor'), ('citizen', 'Citizen'), ('auditor', 'Auditor'), ('court_authority', 'Court Authority')], default='citizen', help_text='User role in the system', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('rejected', 'Rejected'), ('frozen', 'Frozen')], default='pending', help_text='Current status of the land parcel', max_length=20),
        ),
    ]
