# Generated by Django 5.1.3 on 2025-10-12 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0002_alter_user_options_dispute_resolver_parcel_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='metadata_uri',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='token_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='encrypted_private_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_documents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dispute',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the dispute', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the land parcel', null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='location',
            field=models.CharField(blank=True, help_text='Location description of the land parcel', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='dispute_evidence/'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='land_registry.parcel'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'court'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area',
            field=models.FloatField(help_text='Area in square meters'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='GeoJSON coordinates of the parcel boundaries', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='verification_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('surveyor', 'Surveyor'), ('citizen', 'Citizen'), ('court', 'Court Authority')], default='citizen', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
