# Generated by Django 5.2.7 on 2025-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0003_alter_dispute_options_alter_parcel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
