# Generated by Django 5.2.7 on 2025-10-12 10:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0004_user_encrypted_private_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='blockchain_tx_hash',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='verification_data',
        ),
        migrations.AddField(
            model_name='parcel',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='token_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('register', 'Registration'), ('transfer', 'Transfer'), ('update', 'Update'), ('dispute', 'Dispute')], max_length=20)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='land_registry.parcel')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
