# Generated by Django 5.2.7 on 2025-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0005_alter_parcel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={},
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='ipfs_hash',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='token_id',
        ),
        migrations.AddField(
            model_name='parcel',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='verification_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area',
            field=models.FloatField(help_text='Area in square meters'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='GeoJSON coordinates of the parcel boundaries', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the land parcel', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(blank=True, help_text='Location description of the land parcel', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
