# Generated by Django 5.2.7 on 2025-10-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
