# Generated by Django 5.2.7 on 2025-10-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0008_alter_parcel_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
