# Generated by Django 5.2.7 on 2025-10-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0009_alter_parcel_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='surveyor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'surveyor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_surveys', to=settings.AUTH_USER_MODEL),
        ),
    ]
