# Generated by Django 5.2.7 on 2025-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0011_user_email_verified_at_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Indicates if this parcel was imported from a legacy system'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='legacy_document',
            field=models.FileField(blank=True, help_text='Upload legacy paper documents related to this land parcel', null=True, upload_to='legacy_documents/'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('surveyed', 'Surveyed'), ('active', 'Active'), ('disputed', 'Disputed'), ('locked', 'Locked'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
