# Generated by Django 5.2.7 on 2025-11-01 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0012_parcel_is_legacy_parcel_legacy_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from the registrar regarding approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'registrar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_transfer', 'Property Transfer'), ('property_received', 'Property Received'), ('transfer_approval_request', 'Transfer Approval Request'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('dispute_filed', 'Dispute Filed'), ('dispute_resolved', 'Dispute Resolved'), ('system_alert', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='land_registry.parcel')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='land_registry.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
