# Generated by Django 5.2.7 on 2025-11-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0013_add_parcel_history_tracking'),
        ('land_registry', '0013_transaction_approval_notes_transaction_approved_at_and_more'),
    ]

    operations = [
    ]
