# Generated by Django 5.2.7 on 2025-11-01 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0014_merge_20251101_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownershipchain',
            options={'ordering': ['-ownership_start_date']},
        ),
        migrations.AlterModelOptions(
            name='parcelhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='surveyhistory',
            options={'ordering': ['-survey_date']},
        ),
        migrations.RenameField(
            model_name='parcelhistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='ownershipchain',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='original_surveyor',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='survey_number',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='village_tehsil',
        ),
        migrations.RemoveField(
            model_name='parcelhistory',
            name='change_reason',
        ),
        migrations.RemoveField(
            model_name='parcelhistory',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='parcelhistory',
            name='previous_value',
        ),
        migrations.RemoveField(
            model_name='parcelhistory',
            name='related_transaction',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='area',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='survey_documents',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='survey_type',
        ),
        migrations.AddField(
            model_name='ownershipchain',
            name='is_current_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipchain',
            name='transfer_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_registry.transaction'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='district_name',
            field=models.CharField(blank=True, help_text='District where the land is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='original_document_reference',
            field=models.CharField(blank=True, help_text='Reference to original government document', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='original_registrar',
            field=models.ForeignKey(blank=True, help_text='Registrar who processed the original registration', limit_choices_to={'role': 'registrar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_registered_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='original_survey_number',
            field=models.CharField(blank=True, help_text='Original survey number from government records', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='state_name',
            field=models.CharField(blank=True, help_text='State where the land is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='village_name',
            field=models.CharField(blank=True, help_text='Village where the land is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcelhistory',
            name='new_data',
            field=models.JSONField(blank=True, help_text='New state of the data', null=True),
        ),
        migrations.AddField(
            model_name='parcelhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelhistory',
            name='previous_data',
            field=models.JSONField(blank=True, help_text='Previous state of the data', null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='accuracy_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='equipment_used',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='new_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='new_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='previous_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='previous_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='survey_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownershipchain',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='ownershipchain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownershipchain',
            name='ownership_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownershipchain',
            name='ownership_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ownershipchain',
            name='previous_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownershipchain',
            name='transfer_method',
            field=models.CharField(blank=True, help_text='How ownership was acquired', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='original_area',
            field=models.FloatField(blank=True, help_text='Original area as recorded during first registration', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='original_coordinates',
            field=models.JSONField(blank=True, help_text='Original coordinates from first survey', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='original_owner',
            field=models.ForeignKey(blank=True, help_text='The first owner who registered this land', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_owned_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='original_registration_date',
            field=models.DateTimeField(blank=True, help_text='Date when the land was first registered', null=True),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='change_type',
            field=models.CharField(choices=[('registration', 'Initial Registration'), ('ownership_transfer', 'Ownership Transfer'), ('survey_update', 'Survey Update'), ('status_change', 'Status Change'), ('data_update', 'Data Update'), ('dispute_filed', 'Dispute Filed'), ('dispute_resolved', 'Dispute Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='land_registry.parcel'),
        ),
        migrations.AlterField(
            model_name='surveyhistory',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='surveyhistory',
            name='survey_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='surveyhistory',
            name='survey_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyhistory',
            name='surveyor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'surveyor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ownershipchain',
            index=models.Index(fields=['parcel', '-ownership_start_date'], name='land_regist_parcel__7ff4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershipchain',
            index=models.Index(fields=['owner', '-ownership_start_date'], name='land_regist_owner_i_3ba260_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershipchain',
            index=models.Index(fields=['is_current_owner'], name='land_regist_is_curr_3cf861_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelhistory',
            index=models.Index(fields=['parcel', '-timestamp'], name='land_regist_parcel__041699_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelhistory',
            index=models.Index(fields=['change_type', '-timestamp'], name='land_regist_change__bac7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyhistory',
            index=models.Index(fields=['parcel', '-survey_date'], name='land_regist_parcel__a0ba08_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyhistory',
            index=models.Index(fields=['surveyor', '-survey_date'], name='land_regist_surveyo_72d6c8_idx'),
        ),
        migrations.RemoveField(
            model_name='ownershipchain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ownershipchain',
            name='related_transaction',
        ),
        migrations.RemoveField(
            model_name='ownershipchain',
            name='sequence_number',
        ),
        migrations.RemoveField(
            model_name='ownershipchain',
            name='transfer_document',
        ),
    ]
