# Generated by Django 5.2.7 on 2025-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0015_alter_ownershipchain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
    ]
