# Generated by Django 5.2.7 on 2026-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("land_registry", "0016_add_unique_blockchain_tx_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="ipfs_data_hash",
            field=models.CharField(
                blank=True,
                help_text="IPFS hash of complete parcel data",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="mother_patta_ipfs_hash",
            field=models.CharField(
                blank=True,
                help_text="IPFS hash of mother patta document",
                max_length=100,
                null=True,
            ),
        ),
    ]
