# Generated by Django 5.2.7 on 2026-01-19 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("land_registry", "0017_add_ipfs_storage_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("landcore", "LandCore"),
                            ("landverify", "LandVerify"),
                            ("landaudit", "LandAudit"),
                            ("landexchange", "LandExchange"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(help_text="Module description and capabilities"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Required for all licenses"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "License Module",
                "verbose_name_plural": "License Modules",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Unique license identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("institution", "Institution License"),
                            ("department", "Department License"),
                            ("api", "API License"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        help_text="State/District/Department name", max_length=255
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        help_text="e.g., State Government, District Administration",
                        max_length=100,
                    ),
                ),
                (
                    "jurisdiction_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jurisdiction_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("primary_contact_name", models.CharField(max_length=255)),
                ("primary_contact_email", models.EmailField(max_length=254)),
                (
                    "primary_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "max_users",
                    models.IntegerField(
                        default=10, help_text="Maximum number of users"
                    ),
                ),
                (
                    "max_api_calls_per_month",
                    models.IntegerField(
                        default=1000, help_text="Maximum API calls per month"
                    ),
                ),
                ("current_user_count", models.IntegerField(default=0)),
                ("current_month_api_calls", models.IntegerField(default=0)),
                ("api_calls_reset_date", models.DateField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash for blockchain audit trail",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        help_text="Enabled modules",
                        related_name="licenses",
                        to="land_registry.licensemodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Government License",
                "verbose_name_plural": "Government Licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("new", "New License"),
                            ("upgrade", "Module Upgrade"),
                            ("renewal", "License Renewal"),
                            ("modification", "License Modification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("institution_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("justification", models.TextField(help_text="Reason for request")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="land_registry.license",
                    ),
                ),
                (
                    "requested_modules",
                    models.ManyToManyField(
                        related_name="license_requests",
                        to="land_registry.licensemodule",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_license_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_license_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "License Request",
                "verbose_name_plural": "License Requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_institution_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_users",
                        to="land_registry.license",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution User",
                "verbose_name_plural": "Institution Users",
                "indexes": [
                    models.Index(
                        fields=["user", "license"],
                        name="land_regist_user_id_6198be_idx",
                    )
                ],
                "unique_together": {("user", "license")},
            },
        ),
        migrations.CreateModel(
            name="LicenseAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "License Created"),
                            ("activated", "License Activated"),
                            ("suspended", "License Suspended"),
                            ("renewed", "License Renewed"),
                            ("expired", "License Expired"),
                            ("module_added", "Module Added"),
                            ("module_removed", "Module Removed"),
                            ("upgrade_requested", "Upgrade Requested"),
                            ("upgrade_approved", "Upgrade Approved"),
                            ("upgrade_rejected", "Upgrade Rejected"),
                            ("user_added", "User Added"),
                            ("user_removed", "User Removed"),
                            ("api_limit_reached", "API Limit Reached"),
                            ("revoked", "License Revoked"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Additional action details"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="land_registry.license",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "License Audit Log",
                "verbose_name_plural": "License Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["license", "-timestamp"],
                        name="land_regist_license_fdd2ed_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="land_regist_action_b6948e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_number"], name="land_regist_license_ee63eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["status", "valid_until"], name="land_regist_status_a5837b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["institution_name"], name="land_regist_institu_17e0b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licenserequest",
            index=models.Index(
                fields=["status", "request_type"], name="land_regist_status_ac20a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licenserequest",
            index=models.Index(
                fields=["submitted_at"], name="land_regist_submitt_d91fe2_idx"
            ),
        ),
    ]
